ayufan: dev.mk: fix gitlab-ci configs
Change-Id: I80b1f9ff263ab3c7ffd710b47653714e443ac941

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,6 +16,30 @@ build:
   stage: build
   only: [branches]
   script:
+    - rm -f ../*.deb
+    - |
+      set -x
+
+      all_pipeline_ids() {
+        for i in $(seq 1 "${2:-10}"); do
+          result=$(curl "https://gitlab.com/$1/pipelines.json?page=$i" |
+            jq -r '.pipelines[].id')
+
+          [[ -z "$result" ]] && return 0
+          echo "$result"
+        done
+
+        echo "all_pipeline_ids: failed to get all ids" 1>&2
+        return 1
+      }
+
+      get_pipeline_iid() {
+        all_pipeline_ids "$1" "$3" | jq -r "select(. <= $2)" | wc -l
+      }
+
+      export RELEASE=$((1000+$(get_pipeline_iid "$CI_PROJECT_PATH" "$CI_PIPELINE_ID")))
+
+      echo "Current release is $RELEASE."
     - ./dev-make kernel-package
     - |
       set -x
